# Generated by Django 6.0.6 on 2026-06-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_status_rating_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.route'),
        ),
    ]
