# Generated by Django 6.0.6 on 2026-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_transport_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='from_province',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_province',
            field=models.CharField(max_length=255),
        ),
    ]
