# Generated by Django 6.0.5 on 2026-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatmessage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
