# Generated by Django 6.0.5 on 2026-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_is_online_to_driver_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='doc_type',
            field=models.CharField(choices=[('LICENSE_WITH_ID', 'Driver License with Self ID Card'), ('VEHICLE_REGISTRATION', 'Vehicle Registration (Tech Passport)'), ('CAR_PHOTO', 'Car Interior / Exterior Photo')], default='LICENSE_WITH_ID', max_length=25),
        ),
    ]
