# Generated by Django 6.0.5 on 2026-06-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_vehicle_registration_car_photo_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_province',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('samarkand', 'Samarkand'), ('sirdaryo', 'Sirdaryo'), ('surkhandarya', 'Surkhandarya'), ('tashkent_city', 'Tashkent City'), ('tashkent_region', 'Tashkent Region')], default='tashkent_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.route'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_province',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('samarkand', 'Samarkand'), ('sirdaryo', 'Sirdaryo'), ('surkhandarya', 'Surkhandarya'), ('tashkent_city', 'Tashkent City'), ('tashkent_region', 'Tashkent Region')], default='tashkent_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='from_province',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('samarkand', 'Samarkand'), ('sirdaryo', 'Sirdaryo'), ('surkhandarya', 'Surkhandarya'), ('tashkent_city', 'Tashkent City'), ('tashkent_region', 'Tashkent Region')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_province',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('samarkand', 'Samarkand'), ('sirdaryo', 'Sirdaryo'), ('surkhandarya', 'Surkhandarya'), ('tashkent_city', 'Tashkent City'), ('tashkent_region', 'Tashkent Region')], max_length=50),
        ),
    ]
