# Generated by Django 6.0.6 on 2026-07-07 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_province_textchoices_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('share_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('found', 'Item Found'), ('not_found', 'Item Not Found')], default='open', max_length=20)),
                ('driver_response', models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes, I have it'), ('no', 'No, I could not find it')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_item_reports_received', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_item_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_item_report', to='main.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
